export const metadata = {
  title: "Kan Tetris",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0, height: "100%" }}>{children}</body>
    </html>
  );
}
